name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH でデプロイ
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ 160.251.250.138 }}
          username: ${{ student34 }}
          password: ${{ GumaLCx0ZW7B }}
          script: |
            cd ~/chat-app
            git pull origin main
            npm install --production
            pm2 restart chat